linters:
  enable:
    - staticcheck
    - wastedassign
    - unparam
    - tparallel
    - thelper
    - tenv
    - nilnil
    - nilerr
    - nestif
    - nakedret
    - misspell
    - musttag
    - makezero
    - maintidx
    - bodyclose
    - cyclop
    - contextcheck
    - decorder
    #- depguard
    - errorlint
    - exportloopref
    - gocognit
    - gocritic
    - gocyclo
    - unconvert
    - wrapcheck
    - reassign
    - noctx
    - ireturn
    - interfacebloat
    - gofmt
    - godox
    - errname
    - asasalint
    - bidichk
    - dogsled
    - dupl
    - dupword
    - execinquery
    - goconst
    - godot
    - gomnd
    - loggercheck
    - nosnakecase